### ISSUE TITLE
Node process goes out of memory while parsing large JSON files

### ISSUE THREAD

**Issue by crdesai** [dominictarr/JSONStream#101]
I am trying to parse large JSON files which are basically dump of our database in JSON format. It contains a JSON object with table names as key, and array of table data as value. I have a 200MB file and the memory goes upto 2GB, while CPU goes to 100% while processing that file. 
I am trying to parse the file and put the JSON objects parsed into Mongo DB database. is this supported? How can I make it work with smaller memory footprint and CPU?

**Comment by dominictarr** [comment]
this is exactly what JSONStream is good at, but you still have to use it right. what is the structure of your data? and what pattern are you using?

probably you want something like

`JSONStream.parse('*.*')` //parse the rows in each table.

**Comment by crdesai** [comment]
My structure looks something like this.
```
dump:{
    "tabe1": [{
        "col1": "value1",
        "col2": "value2",
        ...
        ...
        "coln": "valuen"
    }, {
        "col1": "value1",
        "col2": "value2",
        ...
        ...
        "coln": "valuen"
    }],
    "table2": [{
      "col1": "value1",
        "col2": "value2",
        ...
        ...
        "coln": "valuen"
    }, {
        "col1": "value1",
        "col2": "value2",
        ...
        ...
        "coln": "valuen"
    }],
    ....
    ....
    "table240": [{
    "col1": "value1",
        "col2": "value2",
        ...
        ...
        "coln": "valuen"
    }, {
        "col1": "value1",
        "col2": "value2",
        ...
        ...
        "coln": "valuen"
    }]
}
```
I hope you get the idea. JSON data consists of an object comprised of table names as Keys and rows as an array of Values. It may have some invalid space characters or line breaks, but JsonStream is able to parse it fine with `JsonStream.parse("*")`. However, it seems JsonStream keeps the entire the parse Json data in memory, so memory increases beyong 2GB for 200MB file and CPU spikes to 100% causing the process to fail if NodeJS process does not have that much memory. 

Is it possible to run JsonStream on 200MB file without such a high memory and CPU requirement.?

**Comment by dominictarr** [comment]
you can't even use JSON.parse on 200 mb, even if you have 2gb. I guess js objects take more space.
i think for this structure you want: `JSONStream.parse('*.*.*')` ?

**Comment by crdesai** [comment]
I a not sure I understand your response. I am getting the right key and value using `JSONStream.parse("$*")`. This gives the right data to retrieve. My problem is the high memory and CPU footprint. Can JSONStream release the key-value pair that has been processed already? It looks like it is keeping the whole JSON object being parsed in memory.

**Comment by dominictarr** [comment]
You are parsing each entire table array in one go, but what you need is to get each _row_, if JSONStream works at all, this is your chance.
Please try `*.*.*` and see if that parses the entire thing without crashing? (try this outside of your app, just a simple script so you know that nothing else is messing with it)

**Comment by crdesai** [comment]
I did try `*.*.*`. However, that gives me individual array values. That is not my intention. My goal is to retrieve table name keys `"table1, table2, etc.` above to create Mongo collections of the same name and then insert the associated value array 
```
[{
    "col1": "value1",
        "col2": "value2",
        ...
        ...
        "coln": "valuen"
    }, {
        "col1": "value1",
        "col2": "value2",
        ...
        ...
        "coln": "valuen"
    }]
```
into appropriate collection.
Correct me if I am wrong, but it looks like JSONStream keeps the parsed JSON object into memory which increases the memory footprint. Is it possible to throw the already parsed objects that are processed and only keep the object being processed right now in memory?

**Comment by dominictarr** [comment]
but does `*.*.*` give you a memory error? if not then we can find a way to get the keys you need.

**Comment by crdesai** [comment]
No it does not give me memory error. It takes a longer time to process the file, but memory and CPU remain low. I tested it with `*.*` also. This one also does not give me memory error, CPU goes upto 80% but does not error out atleast.

**Comment by dominictarr** [comment]
if you had the tablename key, could you insert each row one at a time?

**Comment by crdesai** [comment]
I do not have table name key. I parse the key from JSON file itself, not just value. I do not get how to retrieve key now with `*.*` or `*.*.*`.

**Comment by dominictarr** [comment]
you can't, yet...
but have a look at what this PR did, you basically just need an `{emitPath: true}` option that emits not the top level key, but the keys up to that point, then you'll have what you need.

**Comment by crdesai** [comment]
So basically I cannot emit key or path currently with *.*.*? That means I am stuck with what i want to achieve here. Is that correct understanding?

**Comment by dominictarr** [comment]
no, it just means you need to make a small PR to this module, to create a feature to get the whole path instead of just the last key.

**Comment by crdesai** [comment]
I see. Ok I will work on PR.
Meanwhile, is it possible to not parse a key data? I have a "History" table which I do would like to ignore while parsing. It is not relevant to my use case and is usually very large slowing the process. I would like to filter it from parsing logic. Is it possible?

**Comment by dominictarr** [comment]
if you pass in a JS array (instead of string) you can use a function or a regular expression (if i recall) and so you can filter that way. It's been a long time since I wrote this module...

**Comment by crdesai** [comment]
I am parsing a file so I do not think passing JS array is an option here. Will you be working on this module going forward? I am just trying to understand what to expect going forward with the tool.

**Comment by dominictarr** [comment]
I'm not actively developing it anymore (loads of people use it, but it's very stable).
but I do merge a pull request or respond to issues occasionally.

**Comment by sambua** [comment]
Hi, recently I had the same issue.
Adding small trick with `setInterval` to resume function solved my issue. My file size was 360MB. 
`// Will delay resume time
function delayResumeTime( jstr ) {
  setInterval(function() {
    jstr.resume();
  }, 3000);
}

// And call function where it's require
delayResumeTime(jsonStream);`

Hope it can help, regards.

**Comment by fmkone** [comment]
Hi guys, 
Very enlightening discussion. 
How can i read a json file object by object if structure of source json file looks like following?
What should be the expression ? '*.*'  or what?
 [
{
        "col1": "value1",
        "col2": "value2",
        ...
        ...
        "coln": "valuen"
    }, {
        "col1": "value1",
        "col2": "value2",
        ...
        ...
        "coln": "valuen"
    }
]

**Comment by dominictarr** [comment]
@fmkone if you want to read out every row, use `'*'` if you want to read out a `col1` use `'*.col1'`

**Comment by fmkone** [comment]
@dominictarr  thanks. Problem is that it does give me all json objects, but since i need to parse it in JSON, it gives me broken chunk of stream or buffer which causes an error and i miss certain objects. Is there a way that i can definitely pull out 5 or 10 complete object in one stream instead of broken ones?

**Comment by dominictarr** [comment]
@fmkone If it is doing that it's a bug, or you already have invalid javascript. can you make a script that reproduces the problem?

**Comment by brandonros** [comment]
`node --max-old-space-size=8192 yourFile.js`

**Comment by prashathsenthil** [comment]
Do we have a solution for this issue? 

I'm running into the same issue while using JSONStream with * operator, my data structure is similar to what @fmkone has posted.

I ran my app using --expose-gc flag added and could see that the process.memoryUsage().heapUsed keeps increasing. 

the file size i'm dealing with is ~ 4GB

**Comment by inmotionSIEGE** [comment]
Seems to be hitting a similar wall when trying to parse a 1.4 gb file into memory. Any suggestions?

buffer.js:560
      if (encoding === 'utf8') return buf.utf8Slice(start, end);
                                          ^
Error: "toString()" failed
    at stringSlice (buffer.js:560:43)
    at Buffer.toString (buffer.js:633:10)
    at Object.fs.readFileSync (fs.js:601:41)
    at Object.Module._extensions..json (module.js:669:20)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
