### ISSUE TITLE
parse stream of JSON and non-JSON data

### ISSUE THREAD

**Issue by ORESoftware** [dominictarr/JSONStream#141]
I am getting this error:

```console
Error: Invalid JSON (Unexpected "w" at position 0 in state STOP)
    at Parser.proto.charError (/Users/alexamil/WebstormProjects/oresoftware/tap-json-parser/node_modules/jsonparse/jsonparse.js:90:16)
    at Parser.proto.write (/Users/alexamil/WebstormProjects/oresoftware/tap-json-parser/node_modules/jsonparse/jsonparse.js:154:23)
    at Stream.<anonymous> (/Users/alexamil/WebstormProjects/oresoftware/tap-json-parser/node_modules/JSONStream/index.js:23:12)
    at Stream.stream.write (/Users/alexamil/WebstormProjects/oresoftware/tap-json-parser/node_modules/through/index.js:26:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

I believe the error is simply because the data being written to the stream is a mixture of JSON and non-JSON data. I was expecting this package to handle that, as long as the JSON data was altogether (there is no multiplexing here).

Should this package work if there is JSON data interspersed with non-JSON data?

**Comment by ORESoftware** [comment]
So I am hoping I am not overlooking something. I was able to create a JSON parsing transform stream, by just using try/catch on each complete line of stdout:

https://github.com/ORESoftware/tap-json-parser/blob/master/index.ts

This seems way simpler than the implementation used by this module. Not sure which is more performant, or perhaps mine will fail on edge cases, dunno.

**Comment by dominictarr** [comment]
no this module does not handle json intermixed with with other data.

**Comment by dominictarr** [comment]
yup, if you have control of the source, using new line delimited json is a much better option!
this module is for parsing very large valid JSONs.

**Comment by ORESoftware** [comment]
@dominictarr thanks for the info, I will ask @creationix about jsonparse too
