### ISSUE TITLE
 Unhandled stream error in pipe

### ISSUE THREAD

**Issue by funerr** [dominictarr/JSONStream#52]
The code:
```
var request = http.get(someURL, function(response) {
			response.pipe(JSONStream.parse(...
```

The call stack: 
```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Unexpected "!" at position 1 in state START
    at Parser.proto.charError (...\node_modules\JSONStream
\node_modules\jsonparse\jsonparse.js:84:16)
    at Parser.proto.write (...\node_modules\JSONStream\nod
e_modules\jsonparse\jsonparse.js:112:23)
    at Stream.<anonymous> (...\node_modules\JSONStream\ind
ex.js:21:12)
    at Stream.stream.write (...\node_modules\JSONStream\no
de_modules\through\index.js:26:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at _stream_readable.js:579:7
    at process._tickCallback (node.js:442:13)
```

What am I doing wrong?

**Comment by juliangruber** [comment]
looks like the response isn't valid json, can you do

```js
response.on('data', console.log)
```

and give us the output?

**Comment by funerr** [comment]
Thanks, it was it, some page decided to return html instead of JSON. Maybe we should return a move indicative error message? (eg "not valid JSON")

**Comment by dominictarr** [comment]
@funerr sure, send a pull request.
