### ISSUE TITLE
JSONStream > 0.10 fails on nested objects

### ISSUE THREAD

**Issue by slang800** [dominictarr/JSONStream#81]
This is what I get when I install `JSONStream@0.10`:
```
$ echo '{"bar":{"foo":"baz"}}' | node_modules/.bin/JSONStream '.bar.foo'
["baz"]
```

But this is what I get when I install `JSONStream@1.0.6` (or any other version after `0.10`):
```
$ echo '{"bar":{"foo":"baz"}}' | node_modules/.bin/JSONStream '.bar.foo'
["baz"/usrdata/proj/scraping/instagram-screen-scrape/node_modules/JSONStream/index.js:71
            this.stack[j].value = null
                                ^

TypeError: Cannot set property 'value' of undefined
    at Parser.parser.onValue (/usrdata/proj/scraping/instagram-screen-scrape/node_modules/JSONStream/index.js:71:33)
    at Parser.proto.emit (/usrdata/proj/scraping/instagram-screen-scrape/node_modules/jsonparse/jsonparse.js:350:8)
    at Parser.proto.pop (/usrdata/proj/scraping/instagram-screen-scrape/node_modules/jsonparse/jsonparse.js:345:8)
    at Parser.proto.onToken (/usrdata/proj/scraping/instagram-screen-scrape/node_modules/jsonparse/jsonparse.js:416:12)
    at Parser.parser.onToken (/usrdata/proj/scraping/instagram-screen-scrape/node_modules/JSONStream/index.js:94:12)
    at Parser.proto.write (/usrdata/proj/scraping/instagram-screen-scrape/node_modules/jsonparse/jsonparse.js:101:34)
    at Stream.<anonymous> (/usrdata/proj/scraping/instagram-screen-scrape/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/usrdata/proj/scraping/instagram-screen-scrape/node_modules/through/index.js:26:11)
    at Socket.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
```

**Comment by dominictarr** [comment]
hmm, that definately looks like a bug. can you make a test case PR for this?

**Comment by lencioni** [comment]
It looks like this has been fixed in 1.1.2 and this issue can be closed.
